### ISSUE TITLE
DbConnection or IO(DbConnection)

### ISSUE THREAD

**Issue by tonyday** [DrBoolean/mostly-adequate-guide#106]
Hi

[@DrBoolean - Thank you. Great content and (for my taste) an eminently readable style. It is rare for technical book to make me chuckle.]

In Chapter 8 I am battling to figure out how `connectDb` has a type of `Config -> Either(Error, IO(DbConnection))` given that `Postgres.connect` only has a type of `Url -> DbConnection`.
How does the `DbConnection` become an `IO(DbConnection)` ?
Am I confused or is there an `IO.for` missing somewhere ?

**Comment by xujihui1985** [comment]
yes, I have the same confuse, 

```
// dbUrl :: Config -> Either(Error, url)
var dbUrl = function(c) {
  return (c.uname && c.pass && c.host && c.db)
    ? Right.of("db:pg://"+c.uname+":"+c.pass+"@"+c.host+"5432/"+c.db)
    : Left.of(Error("Invalid config!"));
}
```
dbUrl takes a config object and return an Either monad, and connectDb map over it, calling it should return an `Either(Error, DbConnection)`

```
//  connectDb :: Config -> Either(Error, DbConnection)
var connectDb = compose(map(Postgres.connect), dbUrl);
```

**Comment by DrBoolean** [comment]
Totally correct! Sorry, that's my mistake. Good eyes :) I'll update.
