### ISSUE TITLE
Chapter 10: Applicative Functors link does not work

### ISSUE THREAD

**Issue by bgvianyc** [DrBoolean/mostly-adequate-guide#112]
Perhaps it just a place holder for a chapter that does not yet exist, but chapter 10 is not in the repo although chapter 9 contain a link to it.

**Comment by DrBoolean** [comment]
You're correct. It's a placeholder. Probably best to remove it, but I'm going to try to publish the chapter this week sometime. I'll hold off on doing this for future chapters
