### ISSUE TITLE
Maybe chain / join

### ISSUE THREAD

**Issue by j3k0** [DrBoolean/mostly-adequate-guide#113]
Hello, thanks for great book: eyes opening!

I've got a doubt concerning `Maybe.join` (thus `Maybe.chain`).

When I do `f(a).map(g)`

Given:
```
f :: a → Maybe(a)
g :: a → Maybe(a)
```

Then:
 * If `f` and `g` succeeds, return type is `Maybe(Maybe(a))`
 * If `f` fails, g isn't executed, return type is `Maybe(null)`

So when I `join` I either have a `Maybe(a)` or `null`... which isn't convenient for later processing.

I fixed it by writing: `Maybe.join = isNothing() ? Maybe.of(null) : __value`

Is that correct? Is there something else I missed or a better way?

Thanks!

**Comment by DrBoolean** [comment]
Hi! You are so right! I found this bug the other day and haven't updated yet. Really important fix on my part, I'll do this asap.

**Comment by DrBoolean** [comment]
https://github.com/DrBoolean/mostly-adequate-guide/commit/a73fcb72da98f4e2b08ed077f440f7ed07630696

Just like ya said.

**Comment by j3k0** [comment]
@DrBoolean Just a very tiny improvement on this mater (I found since then):

`isNothing() ? Maybe.of(null) : __value`

can be more concisely written:

`isNothing() ? this : __value`

Thanks again for the great gitbook :+1: I'm sooooo looking forward to chapter 10!

**Comment by DrBoolean** [comment]
That's definitely more concise and efficient memory-wise. We made the decision earlier to return the explicit `Maybe.of(null)` for learning purposes and also to avoid the unintentional `Maybe(undefined)` as a return value. I definitely agree that `this` is better in production.
