### ISSUE TITLE
Rename map to fmap

### ISSUE THREAD

**Issue by gyzerok** [DrBoolean/mostly-adequate-guide#122]
What do you think about renaming ```map``` to ```fmap``` for functors. So we can eliminate confusion in this. The point is that map usually used to map collections, not single values.

**Comment by zerkms** [comment]
I've had similar thoughts after a friend of mine asked me how to distinguish between a `map` and a `map`

**Comment by DrBoolean** [comment]
I wholeheartedly subscribe to https://github.com/fantasyland/fantasy-land as the official JS spec for this stuff. If we want to rename it, we should ask them there.
