### ISSUE TITLE
What's the regex supposed to do in dasherize in chapter 5?

### ISSUE THREAD

**Issue by despairblue** [DrBoolean/mostly-adequate-guide#124]
```javascript
var dasherize = compose(join('-'), map(replace(/\s{2,}/ig, ' ')), split(' '))
```

I can't think of any useful application :confused:

**Comment by DrBoolean** [comment]
In my tests, it removes any space of 2 or more and replaces it with 1. So a string like `"hello     world"` will end up being `"hello world"`. I'm open to a better regex though - I don't consider myself an expert.

**Comment by despairblue** [comment]
After `split(' ')` there can't be any spaces left. This should be:

```javascript
var dasherize = compose(join('-'), split(' '), replace(/\s{2,}/ig, ' '))
```

Right? Or am I missing something?

**Comment by DrBoolean** [comment]
You are totally right. Let's simply this puppy!

**Comment by despairblue** [comment]
Since the point is to show how `trace` works we're probably in the need of another example. Maybe sprinkle a `toLower` in there?

**Comment by DrBoolean** [comment]
Agreed. Want to go for it? If not, i can change it
