### ISSUE TITLE
Why don't we need isSameTeam (ch 3)?

### ISSUE THREAD

**Issue by jdart** [DrBoolean/mostly-adequate-guide#126]
Chapter 3 reads "Since our data is immutable, we can simply replace the teams with their actual value", and then the isSameTeam is removed. Doesn't that change the api, as teammates can now punch each other?

**Comment by DrBoolean** [comment]
Hi @jdart.

The idea is not that we're rewriting the code, but rather using equational reasoning to "interpret it" ourselves. So, it would indeed change the api were we to alter the program. I'll try to make this clearer.

Thanks!

**Comment by jdart** [comment]
So equational reasoning is done using specific inputs, ignoring how other inputs would behave differently?

**Comment by DrBoolean** [comment]
Hi @jdart, I see what you're saying. I think where the confusion is coming from is that I'm using the particular example with Jobe and Michael to reason about this particular evaluation. We can run through it with different inputs and see how it behaves later. The immutability ensures us that some other process isn't altering our data mid-eval.
