### ISSUE TITLE
wrong definition of curry

### ISSUE THREAD

**Issue by jfbouzereau** [DrBoolean/mostly-adequate-guide#128]
shouldnt curry  be defined as

var curry = require('lodash').curry

and not as

var curry = require('lodash.curry')

**Comment by DrBoolean** [comment]
One can install single methods from lodash with the above syntax

**Comment by jfbouzereau** [comment]
Only if you install it first with

npm install lodash.curry

The chapter 5 advises to run

npm install lodash

which is not sufficient to run the examples

**Comment by JakeChampion** [comment]
@jfbouzereau I think we should probably be using `var curry = require('lodash/function/curry')`

**Comment by DrBoolean** [comment]
sold
