### ISSUE TITLE
Wrong definition of partial order in chapter 5

### ISSUE THREAD

**Issue by rpominov** [DrBoolean/mostly-adequate-guide#130]
Not sure if it's wrong, or I misunderstood something.

Here is the quote:

> What are some other categories, you ask? Well, we can define one for directed graphs with nodes being objects, edges being morphisms, and composition just being path concatenation. We can define one for Numbers **with `>` as morphisms** and **0 as identity**[^actually any partial or total order can be a category]. There are heaps of categories, but for the purposes of this book, we'll only concern ourselves with the one defined above. We have sufficiently skimmed the surface and must move on.

I think the morphisms in a partial order with numbers should be `<=`, the identity should be also `<=` (any number *less or equal* to itself), and `0` could be the *initial object* (in case we don't include negative numbers).

Please check definition of *partial order* from [Categories Great and Small](http://bartoszmilewski.com/2014/12/05/categories-great-and-small/), and of *initial object* from [Products and Coproducts](http://bartoszmilewski.com/2015/01/07/products-and-coproducts/) — chapters from "Category Theory for Programmers" by @BartoszMilewski

**Comment by DrBoolean** [comment]
Thanks @rpominov I did indeed forget to add the `=`. I'm a huge fan of @BartoszMilewski's work! Wonderful stuff.

**Comment by rpominov** [comment]
There is also "... 0 as identity" part. `0` can't be an identity morphism, it's not even a *morphism* but an *object* in that category. It can be the *initial object* though.

**Comment by DrBoolean** [comment]
Goodness, this is all wrong. You're totally correct. Updating again...
