### ISSUE TITLE
`compose(id, f) == compose(f, id) == f` evaluates to false in JavaScript (chapter 5)

### ISSUE THREAD

**Issue by rpominov** [DrBoolean/mostly-adequate-guide#131]
For 2 reasons actually :)

1. `(compose(f, id) == f) === false` because even though functions are equivalent, JavaScript can't detect that equality.
1. After `compose(f, id) == f` evaluates to `false` we are comparing `compose(id, f)` and `false`, which is also `false`.

This line might be correct as a pseudo code, but presence of `var` suggest that it's a JavaScript code.

**Comment by mallowigi** [comment]
yeah it's probably it's execution that give the same result

```
compose(f, id)(x) == f(x))
```

**Comment by DrBoolean** [comment]
I'll write something about how this is not meant to be executed literally. The two functions are equivalent, but js cannot tell that.

**Comment by DrBoolean** [comment]
Thanks @Naissur! I imagine @rpominov understands this, but is pointing out the js literal notation might be confusing as it does indeed evaluate to false. I think removing `var identity =` will remove the confusion

**Comment by rpominov** [comment]
Yeah, I understand of course that `==` supposed to mean functional equality, it just seems confusing together with `var identity =`, so the code looks like JavaScript that actually evaluates to `false` :smile: 

> Awesome book, by the way :+1:

+1, thanks a lot for working on it, @DrBoolean!

**Comment by DrBoolean** [comment]
Thanks! All fixed up.
