### ISSUE TITLE
Practical benefits of using pure future returning functions?

### ISSUE THREAD

**Issue by AriaMinaei** [DrBoolean/mostly-adequate-guide#144]
I understand the benefits of having synchronous functions be pure functions (in any language), and I think I understand the necessity of having pure monadic functions in Haskell and having the runtime manage the side effects.

But within JavaScript's semantics, I don't understand how making future-returning functions to be pure would be beneficial.

Consider this snippet. `f()` is pure and `g()` is not:

```javascript
var Promise = require('Promise');

// f :: a -> _ -> Promise Error Number
function f(a) {
    return function(){
        return new Promise(function(resolve){
            resolve(localStorage.getItem(a));
        });
    }
}

// g :: a -> Promise Error Number
function g(a) {
    return new Promise(function(resolve){
        resolve(localStorage.getItem(a));
    });
}
```

`f()` returns a thunk of a Promise. It doesn't do any execution unless we run the thunk. So it almost acts like a Task from 'folktale/data.task'. `g()` on the other hand starts executing right away.

Now, what's the practical benefit of using `f()` instead of `g()`? Because, the thunk returned from `f()` doesn't really give us any insight into what it plans to do. And we're planning to run that thunk right away anyway.

Or put another way: If we were to use a function like `f()` or `g()` as an action creator in a flux architecture, how would we benefit from using `f()`? What features/assurances/properties would it make possible?

Btw, I'm intentionally not using `data.task` here because my question is not about the benefits of using Tasks instead of Promises. It's only about having pure future-returning functions vs impure ones.

**Comment by KtorZ** [comment]
The thing is, by returning a Promise, you're returning something that you have to use as it is. The idea of encapsulation in functional programming, I mean putting some data into a Functor, allows you to define transformation to apply to your data. 
How do you map something on a Promise while keeping the exact same flow of execution. What is very powerful with purity and Functors, is the way you can just declare what is going to happen. Then, at the end, once every needed transformations have been applied to your data, you can decide what to do with those given data (error, send an error message, or simply return the result). 

By using Promise like this, you'll have to make a disjunction each time, for each promise, and this will break the simple single flow you could have defined using Functors (like a Future / Task). The thing is, by returning a Promise, you're returning something that you have to use as it is. The idea of encapsulation in functional programming, I mean putting some data into a Functor, allows you to define transformation to apply to your data. 
How do you map something on a Promise while keeping the exact same flow of execution. What is very powerful with purity and Functors, is the way you can just declare what is going to happen. Then, at the end, once every needed transformations have been applied to your data, you can decide what to do with those given data (error, send an error message, or simply return the result). 

By using Promise like this, you'll have to make a disjunction each time, for each promise, and this will break the simple single flow you could have defined using Functors (like a Future / Task).

**Comment by AriaMinaei** [comment]
That was a very clear explanation. Thank you @KtorZ :)
