### ISSUE TITLE
Ch.8 withdraw and maybe

### ISSUE THREAD

**Issue by coderasm** [DrBoolean/mostly-adequate-guide#146]
In chapter 8, the part concerning withdrawing from an account using maybes, uses two functions I can not find being defined anywhere. The line:
```javascript
var finishTransaction = compose(remainingBalance, updateLedger);
```
Were those functions left out with the intent to not run this code or were they left to the reader to implement?

**Comment by DrBoolean** [comment]
Hi! Yeah, those were a bit hypothetical. It's difficult since I want to show a real-ish example, but keep complexity down.

They could be as simple as concatting some strings. I should mention it somewhere for sure. Thanks for bringing it up.
