### ISSUE TITLE
Chapter 2: First Class Functions - Why favor first class?

### ISSUE THREAD

**Issue by dusky3** [DrBoolean/mostly-adequate-guide#148]
Shoudn't the following be the other way round?
```
var fs = require('fs');

// scary
fs.readFile('freaky_friday.txt', Db.save);

// less so
fs.readFile('freaky_friday.txt', Db.save.bind(Db));
```

**Comment by DrBoolean** [comment]
I'm not sure I understand. To explain my thinking a little further: the scary portion has an unbound `this` which, if used inside of the `Db.save` method can blow up whereas the bound version will have the correct `this` all the time.

**Comment by dusky3** [comment]
Thank you for the explanation @DrBoolean, now I understand what you meant. It wasn't clear to me from the explanation in the book that's why I think you should add this explanation so all the beginners like me may have a better idea what's going on. Anyway thank you for this great book, I learned a lot.
