### ISSUE TITLE
`split` in chapter 4

### ISSUE THREAD

**Issue by killtheliterate** [DrBoolean/mostly-adequate-guide#19]
Noticed that `split` is missing from https://github.com/DrBoolean/mostly-adequate-guide/blob/master/ch4.md#exercises

```javascript
var split = _.curry(function(splitter, str) {
  return str.split(splitter); 
});
```

**Comment by killtheliterate** [comment]
That may not be adequate (as it's not point-free :P), was just noting that the way the exercise is worded, it read as though split should be supplied.

**Comment by killtheliterate** [comment]
Heh, obviously I don't know Ramda :smile:

**Comment by DrBoolean** [comment]
Good call though! I need to namespace the split fn with R or _
