### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by prakhar1989** [DrBoolean/mostly-adequate-guide#37]
Thanks for this awesome book - and kudos for picking up JS for teaching FP! I have two quick suggestions that might help -

1. ES6 - Features like arrow functions, destructuring, generators etc are quite suited, in my opinion, for cases like this where you can write concise pure functions. I think using these features for code samples / exercises in book would be quite worthwhile. 

```javascript
[1, 2, 3, 4, 5].map((x) => x * x).reduce((a, b) => a + b)
```

2. Gitbook - [Gitbook](https://www.gitbook.com/) is a fantastic format for publishing your books. It takes markdown files and generates beautiful books that look great on all devices. You should definitely consider publishing this guide on Gitbook!

Please share your thoughts on what you think about these ideas. Lastly, I'll be more than happy to send in PRs if you prefer. 

Thanks again for writing this wonderful guide! :beers: 

Disclosure: I'm in no way associated with Gitbook; just a happy reader.

**Comment by DrBoolean** [comment]
I absolutely love the es6 features and babel, but I wanted to keep it simple. Perhaps we can fork it for es6? I'll totally use Gitbook! Thanks for the suggestion - signing up now.

**Comment by DrBoolean** [comment]
https://www.gitbook.com/book/drboolean/mostly-adequate-guide/dashboard (building i guess)

**Comment by prakhar1989** [comment]
That's an internal link. Can you post the public URL?
