### ISSUE TITLE
Relicense to CC-BY-SA?

### ISSUE THREAD

**Issue by kozross** [DrBoolean/mostly-adequate-guide#38]
Is there any chance I can convince you to relicense this work to CC-BY-SA instead of what it is currently? Both NC and ND have several problems you may not be aware of - you can read about them [here][1] and [here][2].

[1]: http://freedomdefined.org/Licenses/NC
[2]: http://freedomdefined.org/Licenses/ND

**Comment by DrBoolean** [comment]
Think I did it right?...

**Comment by kozross** [comment]
The free culture movement thanks you - you've done a very good thing today. :)

**Comment by DrBoolean** [comment]
sweet

**Comment by vyp** [comment]
:+1: :sparkles: :sparkles:
