### ISSUE TITLE
GitBook

### ISSUE THREAD

**Issue by riston** [DrBoolean/mostly-adequate-guide#39]
The books seems to be great, but the format without good navigation is bad. Instead of using simple markdown files the [GitBook](https://github.com/GitbookIO/gitbook) format could be used.

**Comment by theaqua** [comment]
I agree :+1:

**Comment by RPallas92** [comment]
I agree! 
Is it possible to have a printable version?

**Comment by DrBoolean** [comment]
https://www.gitbook.com/book/drboolean/mostly-adequate-guide/dashboard

Waiting on the build...

**Comment by JakeChampion** [comment]
You could use - https://www.lulu.com/

**Comment by DrBoolean** [comment]
http://drboolean.gitbooks.io/mostly-adequate-guide/

**Comment by theaqua** [comment]
Good! Thanks, @DrBoolean.

**Comment by riston** [comment]
Well done, looks much better and easier to read!

**Comment by hemanth** [comment]
:+1:
