### ISSUE TITLE
PDF version

### ISSUE THREAD

**Issue by medikoo** [DrBoolean/mostly-adequate-guide#48]
Are there any plans to generate one PDF out of this files? It'll be handy to have it also in such format

**Comment by hemanth** [comment]
[Here you go](https://www.gitbook.com/download/pdf/book/drboolean/mostly-adequate-guide)

**Comment by medikoo** [comment]
Thank you! I'tll be great to have it linked in README.md

**Comment by stassinari** [comment]
For everyone who'd like epub/mobi formats too, here's the link to the GitBook page of the project.
http://drboolean.gitbooks.io/mostly-adequate-guide/
