### ISSUE TITLE
Add hint about ramda to Exercise in Chapter 4

### ISSUE THREAD

**Issue by mikehaertl** [DrBoolean/mostly-adequate-guide#51]
It would help a lot, if you could add a note about ramda and what it does before the exercise in chapter 4. I was quite confused, because I didn't know that `split()` etc. are provided as curried functions.

**Comment by JohnGurin** [comment]
It's not `ramda`.
This function comes from `require('../../support')`
https://github.com/DrBoolean/mostly-adequate-guide/blob/master/code/part1_exercises/support.js

**Comment by DrBoolean** [comment]
Ahh, good call. Thanks for the thought. I'll work something in for sure

**Comment by jrefano** [comment]
I was also really confused by this example and came here to see if anyone else was.  :+1:

**Comment by DrBoolean** [comment]
https://github.com/DrBoolean/mostly-adequate-guide/commit/be84eee96784f1619ea18e86b1aee2e6373aacbe

Bam!

**Comment by mikehaertl** [comment]
:+1:
