### ISSUE TITLE
nom de plume

### ISSUE THREAD

**Issue by ultranaut** [DrBoolean/mostly-adequate-guide#55]
Is it Professor Frisby (per the cover) or Risby (chapter 1)? Or is the cover meant to be a portmanteau of F. Risby? Is it intended to create an air of mystery? Is he actually a Professor?

I'm going to sit here and be quiet now.

**Comment by DrBoolean** [comment]
Haha, yeah. I actually was going to change it to Professor F. Risby's guide, but i was too lazy to edit the image. It is Franklin Risby, curmudgeon badger

**Comment by ultranaut** [comment]
Say no more, I can get 100% behind laziness.
