### ISSUE TITLE
Answers to examples

### ISSUE THREAD

**Issue by jrefano** [DrBoolean/mostly-adequate-guide#56]
Would be nice to have answers to the examples for each chapter.  Hard to know if one has grasped the concept without knowing if we've completed the example correctly!

Also, this is great stuff!!  Thank you!

**Comment by jrefano** [comment]
oh wait, i found them in the repo.  i guess all that is needed is a link to the answers then.

**Comment by DrBoolean** [comment]
https://github.com/DrBoolean/mostly-adequate-guide/commit/be84eee96784f1619ea18e86b1aee2e6373aacbe

Thanks for letting me know it wasn't as obvious as it should have been
