### ISSUE TITLE
iBooks - The book is corrupt

### ISSUE THREAD

**Issue by DaleJefferson** [DrBoolean/mostly-adequate-guide#59]
I downloaded the epub version from https://www.gitbook.com/download/epub/book/drboolean/mostly-adequate-guide and when I open it in Mac iBooks v1.2 I get an error telling me the book is corrupt.

![screen shot 2015-07-17 at 21 21 16](https://cloud.githubusercontent.com/assets/375005/8756392/dc220b50-2cc9-11e5-942a-df1f1f7b7de7.png)

**Comment by DrBoolean** [comment]
It's an honest book I swear! I'll totally look into this over the weekend...

**Comment by DrBoolean** [comment]
I can't seem to figure out why (might have to do with the subchapters so I'll mess with that), but it does seem to work after i close and reopen for now as a workaround

**Comment by llabball** [comment]
Tested to open it in iBooks on iOS - that works well.

**Comment by DaleJefferson** [comment]
iOS iBooks works great, I'm a couple of chapters in and really enjoying it. I'm not sure how many people read in iBooks on the Mac, it was just the place I downloaded it.
