### ISSUE TITLE
lodash-fp

### ISSUE THREAD

**Issue by jdalton** [DrBoolean/mostly-adequate-guide#60]
Hey Brian! I noticed a couple lodash mentions and thought you'd dig [lodash-fp](https://www.npmjs.com/package/lodash-fp) since its the auto-curried iteratee-first data-last flavor of lodash which fits a bit more with the text.

**Comment by DrBoolean** [comment]
Hey man! I'm 100% pro lodash-fp (since lodash is my preferred utility lib for all things not-curried). I think it's good to incorporate somehow - like put a download link for support libs.

**Comment by jdalton** [comment]
Ya, that'd rock.

**Comment by hemanth** [comment]
`ramda` :heart_eyes: `lodash-fp`

^ This is why I :heart: JS community :+1:

**Comment by DrBoolean** [comment]
https://github.com/DrBoolean/mostly-adequate-guide/commit/be84eee96784f1619ea18e86b1aee2e6373aacbe

Boom!
