### ISSUE TITLE
OO Seagulls

### ISSUE THREAD

**Issue by vjau** [DrBoolean/mostly-adequate-guide#63]
Hi,
i have just started to read your book, thank you for it !
However, i was a bit disturbed by the example of oo code you wrote in the "flock of seagulls" part.
This part is supposed to show some advantages of FP over OO, but i think it's demonstrating how NOT to code in OO !

As you wrote :
> Contrast this with our absurd object version which ignores built in functions and data types in order > to model the "real world". 

I don't know what it's supposed to model, but it's not the real world !
You are instantiating three Flock objects, each with an initial size. I'm not sure instantiating a zero sized flock (as you did with flock_c) means anything in real life, i probably would have forced the constructor to throw when passing zero as a parameter or to return undefined, but that's not the important point there.
The big problem comes from the actual heart of the program, as you call it the "ghastly abomination".
Here it is :
```js
var result = flock_a.conjoin(flock_c).breed(flock_b).conjoin(flock_a.breed(flock_b)).seagulls;
```
What the heck is this supposed to mean ? 
What real world problem is this supposed to represent ?
Let's try to understand:
##### First Step
flock_a join with flock_c (remember, it's a zero sized flock, if that mean anything).
So the flocks are joining, they becomes one only flock, the members of flock_c are coming into flock_a or the opposite. Is it not a very good case for state modification ? What does it mean to take two flocks as parameters and get a new flock ? Does it really make sense to make the flocks immutable ? After flock_c has joined flock_a, is there still a flock_c ? Can we say that flock_a has not changed ? (actually it has not since flock_c has zero members, but let's pretend the opposite).
Is the adding of flock_c members really an addition of two immutable value or the mutation of flock_a state and the disapearance of flock_c ?
I vote for this last propostion, and i write this operation like this :
```js
flock_a.conjoin(flock_c);
```
How could this be simpler ?
I could even add a method on Flock that would put the population at zero when consumed by Flock.conjoin()
Let's do that.
```js
Flock.prototype.empties = function(){
  this.seagulls = 0;
}
```
And modify conjoin accordingly:
```js
Flock.prototype.conjoin = function(other){
  this.seagulls += other.seagulls;
  other.empties();
}
```
And we don't return this, because it violate the law of demeter and makes your code a mess.

##### 2nd step: 

It seams that the result of flock_a joining force with flock_c, which we choose to still call flock_a, is now doing some breeding business with flock_b.
From your defintion in the class, we understand that after a round of reproduction, the child stay with the object whose breeding method was called and the other parent which continue on his own doesn't keep parental authority. So the flock_a population is again modified, and flock_b population doesn't change.  Easy !
```js
flock_a.breed(flock_b);
```
How could this be simpler ?

##### 3rd step :

Now the resulting flock (again flock_a) is joining with the result of flock_a.breed(flock_b) which is also flock_a.... Wow wow wow, stop where you are ! What does it mean in the real world to join a flock with itself ??? I don't get it, are you just counting seagulls or are you breeding/joining them ? 

Ok, perhaps i have not understood the problem correctly, when two flocks breed, they are producing a completely new Flock and are themselves unmodified.
But then the breed method is not correct and should be rewritten like this:
```js
Flock.prototype.breed = function(other) {
  return new Flock(this.seagulls * other.seagulls);
};
```
And that changes everything !
Let's reconsider each steps with this new information.

Step1
```js
flock_a.conjoin(flock_c); // no change flock_a = 4
```
Step2
```js
flock_d = flock_a.breed(flock_b) // flock_d = 8; flock_a = 4; flock_b = 2;
```
Step3
```js
//flock_a.breed(flock_b) return a new Flock which size is 4x2 = 8
//which will then join with flock_a
flock_a.conjoin(flock_a.breed(flock_b)) // flock_a = 8 + 4 = 12; flock_b = 2
```
Now it's finished, we have three discrete flocks, flock_a whose size is 12, flock_b whose size is still 2, flock_d of size 8 (and we still have the fantom flock_c of size 0).

Now, let's enjoy some functionnal programming ;)
```js
var total = [flock_a, flock_b, flock_c, flock_d].reduce(function(total, flock){
  return total + flock.seagulls;
},0);
```
Which gives us a total of 22 ! Not 16, not 32, 22 ! Unless i made a mistake.

I still think that good OO is very handy when modeling reality.

Complete source code to be sure we are on the same page :
```js
var Flock = function(n) {
  "use strict";
  this.seagulls = n;
};

Flock.prototype.empties = function(){
  "use strict";
  this.seagulls = 0;
};

Flock.prototype.conjoin = function(other){
  "use strict";
  this.seagulls += other.seagulls;
  other.empties();
};

Flock.prototype.breed = function(other) {
  return new Flock(this.seagulls * other.seagulls);
};

var flock_a = new Flock(4);
var flock_b = new Flock(2);
var flock_c = new Flock(0);

flock_a.conjoin(flock_c);

var flock_d = flock_a.breed(flock_b);

flock_a.conjoin(flock_a.breed(flock_b));

var total = [flock_a, flock_b, flock_c, flock_d].reduce(function(total, flock){
  return total + flock.seagulls;
},0);

console.log(total);
```

Thank you for your attention !

**Comment by DrBoolean** [comment]
You are certainly correct. It is my fault for not explaining that it is bad code on purpose. I just pushed: https://github.com/DrBoolean/mostly-adequate-guide/commit/d51c5b5f93e856dc39eb765399758526134ca0a2

**Comment by omasback** [comment]
Please explain why 32 is incorrect and 16 is correct. In your seagull class, a flock is able to conjoin with itself and double its own size, therefor 32 is correct. A simple check for equality of flocks in the conjoin method would have prevented this unnatural behavior:

````javascript
Flock.prototype.conjoin = function(other) {
  if (this === other) {
    throw('a flock cannot conjoin with itself!')
  }
  this.seagulls += other.seagulls;
  return this;
};
````

But I don't see a way for the functional approach to prevent self-conjoining, since the functional code is operating on number literals instead of objects. To me, this example is actually an argument against FP.

**Comment by DrBoolean** [comment]
Hi @omasback 

You have a good point - if `flock_a` were to breed with `flock_b` twice, its state probably *should* be altered and the object would keep track for us.

The intention was to show unexpected consequences of using state and custom methods in what should be a very simple program. Well, that and show that mathematical properties can be held if we code within the "framework". I didn't realize it until just now, but it fails miserably to highlight the common problem of unintended mutation as the result is arguably more correct in the OO version.

This is a problem lots of folks (including me) hit when working with mutable state so I'll try to find a better example to demonstrate it.

To answer your question about why I thought `16` was correct:

I was using equational reasoning to run the example in my head. In other words, if I were to replace each variable with its value (knowing numbers don't have breed/conjoin) I was interpreting it as:
```
var result = 4.conjoin(0).breed(2).conjoin(4.breed(2)).seagulls;
var result = 4.breed(2).conjoin(8).seagulls;
var result = 8.conjoin(8).seagulls;
var result = 16;
```
