### ISSUE TITLE
Suggest Gitbook for mobile readers

### ISSUE THREAD

**Issue by amyleesalesforce** [DrBoolean/mostly-adequate-guide#80]
https://www.gitbook.com/

**Comment by csoma** [comment]
From https://github.com/DrBoolean/mostly-adequate-guide/issues/59

### EPUB

https://www.gitbook.com/download/epub/book/drboolean/mostly-adequate-guide

### Mobi (Kindle)

https://www.gitbook.com/download/mobi/book/drboolean/mostly-adequate-guide

### Do it yourself

```
git clone https://github.com/DrBoolean/mostly-adequate-guide.git

cd mostly-adequate-guide/
npm install gitbook-cli -g
gitbook init

brew update
brew cask install calibre

gitbook mobi . ./functional.mobi
```

**Comment by DrBoolean** [comment]
Oh this is so perfect. Thanks!
