### ISSUE TITLE
Chapter 5: example demonstrating associative example doesn't work

### ISSUE THREAD

**Issue by Bondifrench** [DrBoolean/mostly-adequate-guide#98]
See this [jsbin](http://jsbin.com/hafapu/edit?html,js,console,output)

lastUpper as written in tutorial doesn't work unless you group the functions as in lastUpper2 example, or did you modify the compose function?

**Comment by DrBoolean** [comment]
Hi! The paragraph below the example tries to point out that it's more complex than the `compose` written above. Perhaps, we should prefix `compose` with `_` in those examples?

**Comment by Bondifrench** [comment]
That would make it more explicit. 
I think the same should be done with this line: `var reverse = reduce(function(acc, x){ return [x].concat(acc); }, []);` use `_.reduce` to make it explicit that we take them from a library.

**Comment by DrBoolean** [comment]
Yeah, my current overhaul has to do with not relying on previous (or missing) definitions of functions. I'll try to find time this week to use lodash-fp or ramda as much as possible

**Comment by Bondifrench** [comment]
I really appreciate your book as I am relatively new to functional programming, it helps to make my code more readable and declarative.

One interesting feature that might be nice to add within your book, is how you integrate functional paradigms with a framework like [Mithril](http://mithril.js.org/) (my favorite) or React or other libraries like [paths-js](https://github.com/andreaferretti/paths-js) or D3.js for charts, i.e. use cases/real world examples

**Comment by DrBoolean** [comment]
Thanks for the suggestions! For the compose confusion, I'm going to open an issue to replace as many custom functions with `_` so we know where they're coming from and close out this one.
